services:
    JokeStorageService:
        class: App\Joker\Service\JokeStorageService
        arguments:
            # TODO It doesn't work. Why? I tried a few variations - all failed.
            $storageJokesPath: "%kernel.project_dir%/storage/jokes/"
            $storage: "@filesystem"
